services:
  backend:
    image: kimjaehyun158/trai-backend:latest
    container_name: backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "8080"
      
  frontend:
    image: kimjaehyun158/trai-frontend:latest
    container_name: frontend
    expose:
      - "3000"
      
networks:
  trai_network:
    external: true
