name: Backend CI

on:
  push:
    branches:
      - refactor
    paths:
      - 'BE/**'

  pull_request:
    branches:
      - refactor
    paths:
      - 'BE/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      - name: build and test pipeline
        working-directory: ./BE
        run: ./gradlew clean build